apiVersion: v1
kind: Service
metadata:
  name: prometheus-basicservice
  namespace: monitoring 
  labels:
    app: prometheus-basicservice
spec:
  ports:
  - port: 9090
    name: prom-graph
  type: NodePort
  selector:
    app: prometheus-basicservice
