apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-basicservice
  namespace: monitor
  labels:
    app: prometheus-basicservice
data:
  prometheus.yml: >
    global:
      scrape_interval:     60s
      evaluation_interval: 60s

    scrape_configs:

      - job_name: basicservice
        kubernetes_sd_configs:
        - role: pod

        relabel_configs:
        - source_labels: [__meta_kubernetes_pod_namespace]
          action: keep
          regex: inc
        - source_labels: [__meta_kubernetes_pod_container_port_number]
          action: keep
          regex: 9145
        - source_labels: [__meta_kubernetes_pod_name]
          separator: ;
          regex: (.*)
          target_label: pod
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: app
          replacement: $1
          action: replace
        - source_labels: [__meta_kubernetes_pod_label_app]
          separator: ;
          regex: (.*)
          target_label: appId
          replacement: $1
          action: replace
